apiVersion: argoproj.io/v1alpha1
kind: ExecutorPlugin
metadata:
  name: containerless
spec:
  sidecar:
    # TODO: Not possible (yet!)
    # volumes:
    #   - name: pv-storage
    #     persistentVolumeClaim:
    #       claimName: pv-claim
    container:
      command:
        - /home/debian/containerless
      image: mycluster-registry:50959/containerless:local
      # TODO: Not necessary
      imagePullPolicy: Always
      name: containerless
      env:
        - name: RUST_LOG
          value: "info"
        # - name: PYTHON_WORKDIR
        #   value: "/python"
      ports:
        - containerPort: 8000
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      # TODO: Not possible (yet!)
      # volumeMounts:
      #   - mountPath: "/python"
      #     name: pv-storage