apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: containerless-
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        containerless:
          # Python >= 3.7 is supported
          runtime: python-3.10
          repoURL: https://github.com/pevers/example-python-step.git
          targetRevision: main
          args:
            - "src/example.py"
            - "--some"
            - "parameter"